services:
  auth-db:
    container_name: auth_database
    image: postgres:16.2
    restart: always
    # volumes:
    #   - ./auth-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${AUTH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
      - POSTGRES_DB=${AUTH_POSTGRES_DB}
  task-db:
    container_name: task_database
    image: postgres:16.2
    restart: always
    # volumes:
    #   - ./task-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${TASK_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TASK_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TASK_POSTGRES_DB}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
